include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
  errors:
    invalid_annotation_target: ignore

linter:

  rules:
    avoid_print: true
    prefer_single_quotes: true
    lines_longer_than_80_chars: true
    camel_case_types: true
    camel_case_extensions: true
    require_trailing_commas: true

