name: base_core
description: Function helper
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.2.6
  dio: ^4.0.6
  intl: any
  mime: ^1.0.4
  path: ^1.8.2
  path_provider: ^2.0.15



dev_dependencies:
  flutter_test:
    sdk: flutter
